services:
  mysqldb:
    image: mysql:8.0
    container_name: lab_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lab_reservation
      TZ: Asia/Shanghai  # <--- 修改1: 数据库容器设为北京时间
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - lab-net

  backend:
    build: ./backend
    container_name: lab_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/lab_reservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      TZ: Asia/Shanghai  # <--- 修改3: Java 后端容器设为北京时间
    depends_on:
      - mysqldb
    networks:
      - lab-net

  frontend:
    build: ./frontend
    container_name: lab_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lab-net

networks:
  lab-net:
    driver: bridge

volumes:
  db_data:

